		<footer>
			<div id="rodape">
			<div class="centraliza clearfix">
				<section id="copyright">
					<ul class="lst_menu_rodape">
						<li><a href="index.html" title="Home">Home</a></li>
						<li><a href="a-clinica.html" title="A clínica">A clínica</a></li>
						<li><a href="tratamentos.html" title="Tratamentos">Tratamentos</a></li>
						<li><a href="equipe.html" title="Equipe">Equipe</a></li>
						<li><a href="depoimentos.html" title="Depoimentos">Depoimentos</a></li>
						<li class="ultimo"><a href="contato.html" title="Contato">Contato</a></li>
					</ul>
					<p class="txt_direitos">Telegenética MG &copy; <?=date('Y')?> - Todos os direitos reservados</p>
				</section>

				<section id="localizacao">
					<p class="localizacao">Entre em contato:<br>
					Rua Filipinas, 111 - Loja 04<br>
					Cariru, Ipatinga - MG<br>
					(31) 3825-1966<br>
					nucleovivendi@gmail.com</p>
				</section>

				<div class="bt_topo">
					<a href="javascript:subir();" title="Para o topo"><img src="<?=assets()->img('botoes/bt_topo.gif')?>"></a>
				</div>
			</div>	
			</div>
		</footer>