                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Administrador</h3>

                            <ul class="nav navbar-nav">
                            </ul>
                        </div>                        
                    </div>
                </div>