<!doctype html>
<html lang="pt-BR" dir="ltr">
    <head>
        <title>Clínica Núcleo Vivendi</title>
        <meta name="description" content="" >
        <meta name="keywords" content="">

        <!-- Inclusão do cabeçalho contendo banner, logotipo, telefone principal e menu -->
        <?php $this->render('common/head'); ?>
    </head>
    <body>
        <!-- Inclusão do cabeçalho contendo banner, logotipo, telefone principal e menu -->
        <?php $this->render('common/header'); ?>

        <br><br>
        página de Contato
        <br><br>

        <!-- Inclusão do rodapé -->
        <?php $this->render('common/footer'); ?>
    </body>
</html>