<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <?php if ($dados_equipe): ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Equipe > Alterar</h3>
                            <?php else: ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Equipe > Cadastrar</h3>
                            <?php endif; ?>


                            <ul class="nav navbar-nav">
                                <li><a href="<?= url()->route('index') ?>">Início</a></li>
                                <li><a href="<?= url()->route('clinica.index') ?>">A clínica</a></li>
                                <li><a href="<?= url()->route('tratamentos.index') ?>">Tratamentos</a></li>
                                <li><a href="<?= url()->route('equipe.index') ?>">Equipe</a></li>
                                <li><a href="<?= url()->route('artigos.index') ?>">Artigos</a></li>
                                <li><a href="<?= url()->route('depoimentos.index') ?>">Depoimentos</a></li>
                                <li><a href="<?= url()->route('nutricaofitness.index') ?>">Nutrição e Fitness</a></li>
                                <li><a href="<?= url()->route('receitas.index') ?>">Receitas</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <?php if ($dados_equipe): ?>
                                        <h4>Equipe > Alterar</h4>
                                    <?php else: ?>
                                        <h4>Equipe > Novo</h4>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmCadEquipe" method="POST" action="<?= url()->route('equipe.salvar'); ?>">
                                            <?php if ($dados_equipe): ?>
                                                <input type="hidden" name="id" value="<?= $dados_equipe->cd_membro; ?>">
                                            <?php endif; ?>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nm_membro" class="col-sm-2 control-label text-right">Nome*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_equipe ? $dados_equipe->nm_membro : '' ?>" name="nm_membro" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Registro</label>
                                                <div class="col-sm-10"><input value="<?= $dados_equipe ? $dados_equipe->legenda_membro : '' ?>" name="legenda_membro" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div id="equipe_summernote" class="col-md-12"><label class="col-sm-2 control-label text-right">Currículo</label>
                                                <div class="panel-body col-sm-10">
                                                    <div id="summernote_equipe"></div>
                                                    <textarea style="display:none" name="curriculo_membro" id="curriculo_membro"><?= $dados_equipe ? $dados_equipe->curriculo_membro : '' ?></textarea>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Ativo</label>
                                                <div class="col-sm-10">
                                                    <div class="col-sm-12 padding-0">
                                                        <?php if ($dados_equipe): ?>
                                                            <?php if ($dados_equipe->ativo_membro == 1) : ?>
                                                                <input checked type="checkbox" name="ativo_membro" value="1">
                                                            <?php else : ?>
                                                                <input type="checkbox" name="ativo_membro" value="1">
                                                            <?php endif; ?>
                                                        <?php else : ?>
                                                            <input type="checkbox" name="ativo_membro" value="1">
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button onclick="javascript:window.location.href = '<?= url()->route('equipe.index') ?>';" class="btn ripple btn-raised btn-danger">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="../asset/js/jquery.min.js"></script>
        <script src="../asset/js/jquery.ui.min.js"></script>
        <script src="../asset/js/bootstrap.min.js"></script>


        <!-- plugins -->
        <script src="../asset/js/plugins/moment.min.js"></script>
        <script src="../asset/js/plugins/jquery.knob.js"></script>
        <script src="../asset/js/plugins/ion.rangeSlider.min.js"></script>
        <script src="../asset/js/plugins/bootstrap-material-datetimepicker.js"></script>
        <script src="../asset/js/plugins/jquery.nicescroll.js"></script>
        <script src="../asset/js/plugins/jquery.mask.min.js"></script>
        <script src="../asset/js/plugins/select2.full.min.js"></script>
        <script src="../asset/js/plugins/nouislider.min.js"></script>
        <script src="../asset/js/plugins/jquery.validate.min.js"></script>
        <script src="../asset/js/plugins/summernote.min.js"></script>


        <!-- custom -->
        <script src="../asset/js/main.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {

                $('#summernote_equipe').summernote({
                    height: 300,
                    toolbar: [
                        // [groupName, [list of button]]
                        ['style', ['bold', 'italic', 'underline', 'clear']],
                        ['font', ['strikethrough', 'superscript', 'subscript']]
                    ]
                });

                var curriculo_membro = $('#curriculo_membro').text();

                $("#equipe_summernote .note-editable").html(curriculo_membro);
            });

            function validacaoF(form) {
                $('#lbl_nm_membro').removeClass('alertaFrm');

                if (form.nm_membro.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                    form.nm_membro.focus();
                    $('#msgformulario').html('Nome inválido! Informe-o corretamente.');
                    $('#msgformulario').removeClass('alert-primary');
                    $('#msgformulario').addClass('alert-danger');
                    $('#lbl_nm_membro').addClass('alertaFrm');
                    return false;
                }
            }

            function event_btnEnviarClick()
            {

                var curriculo_membro = $("#equipe_summernote .note-editable").html();
                $('#curriculo_membro').text(curriculo_membro);

                if (validacaoF(document.frmCadEquipe) != false) {
                    document.frmCadEquipe.submit();
                } else {
                    return false;
                }
            }

            $('#btnEnviar').click(event_btnEnviarClick);
        </script>
        <!-- end: Javascript -->
    </body>
</html>