            <div id="left-menu">
                <div class="sub-left-menu scroll">
                    <ul class="nav nav-list">
                        <li><div class="left-bg"></div></li>
                        <li class="time">
                            <h1 class="animated fadeInLeft"></h1>
                            <p class="animated fadeInRight"></p>
                        </li>
                        <li class="active ripple"><a href="<?=url()->route('index')?>"><span class="fa fa-home"></span>Início</a></li>
                        <li class="ripple"><a href="<?=url()->route('aulas.index')?>"><span class="fa fa-graduation-cap"></span>Aulas</a></li>
                        <li class="ripple"><a href="<?=url()->route('login.logout')?>"><span class="fa fa-power-off"></span>Sair</a></li>

                    </ul>
                </div>
            </div>