            <div id="left-menu">
                <div class="sub-left-menu scroll">
                    <ul class="nav nav-list">
                        <li><div class="left-bg"></div></li>
                        <li class="time">
                            <h1 class="animated fadeInLeft"></h1>
                            <p class="animated fadeInRight"></p>
                        </li>
                        <li class="active ripple"><a href="<?=url()->route('index')?>"><span class="fa fa-home"></span>Início</a></li>
                        <li class="ripple">
                            <a class="tree-toggle nav-header"><span class="fa fa-newspaper-o"></span> Público Geral
                                <span class="fa-angle-right fa right-arrow text-right"></span>
                            </a>
                            <ul class="nav nav-list tree">
                                <li><a href="<?=url()->route('aulas.index')?>">Aulas</a></li>
                                <li><a href="<?=url()->route('dicas.index')?>">Dicas</a></li>
                                <li><a href="<?=url()->route('novidades.index')?>">Novidades</a></li>
                                <li><a href="<?=url()->route('dicionario.index')?>">Dicionário</a></li>
                            </ul>
                        </li>
                        <!--
                        <li class="ripple"><a href="<?=url()->route('usuarios.index')?>"><span class="fa fa-user"></span>Usuários</a></li>
                        <li class="ripple"><a href="<?=url()->route('configuracoes.index')?>"><span class="fa fa-wrench"></span>Configurações</a></li>
                        -->
                        <li class="ripple"><a href="<?=url()->route('login.logout')?>"><span class="fa fa-power-off"></span>Sair</a></li>

                    </ul>
                </div>
            </div>