<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <?php if ($dados_textopublico): ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Texto - Pacientes e Familiares > Alterar</h3>
                            <?php else: ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Texto - Pacientes e Familiares > Cadastrar</h3>
                            <?php endif; ?>


                            <ul class="nav navbar-nav">
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <?php if ($dados_textopublico): ?>
                                        <h4>Texto > Alterar</h4>
                                    <?php else: ?>
                                        <h4>Texto > Novo</h4>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmCadTexto" method="POST" action="<?= url()->route('textopacientes.salvar'); ?>">
                                            <?php if ($dados_textopublico): ?>
                                                <input type="hidden" name="id" value="<?= $dados_textopublico->id; ?>">
                                            <?php endif; ?>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_nm_texto" class="col-sm-2 control-label text-right">Título*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_textopublico ? $dados_textopublico->titulo : '' ?>" name="nm_texto" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_chamada_texto" class="col-sm-2 control-label text-right">Chamada*</label>
                                                <div class="col-sm-10"><input value="<?= $dados_textopublico ? $dados_textopublico->chamada : '' ?>" name="chamada_texto" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12"><label class="col-sm-2 control-label text-right">Texto</label>
                                                <div class="panel-body col-sm-10">
                                                    <div id="summernote"></div>
                                                    <textarea style="display:none" name="txt_texto" id="txt_texto"><?= $dados_textopublico ? $dados_textopublico->conteudo : '' ?></textarea>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Palavras-Chave</label>
                                                <div class="col-sm-10"><input value="<?= $dados_textopublico ? $dados_textopublico->keywords : '' ?>" name="keywords_texto" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Descrição</label>
                                                <div class="col-sm-10"><input value="<?= $dados_textopublico ? $dados_textopublico->descricao : '' ?>" name="descricao_texto" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Ativo</label>
                                                <div class="col-sm-10">
                                                    <div class="col-sm-12 padding-0">
                                                        <?php if ($dados_textopublico): ?>
                                                            <?php if ($dados_textopublico->ativo == 1) : ?>
                                                                <input checked type="checkbox" name="ativo_texto" value="1">
                                                            <?php else : ?>
                                                                <input type="checkbox" name="ativo_texto" value="1">
                                                            <?php endif; ?>
                                                        <?php else : ?>
                                                            <input type="checkbox" name="ativo_texto" value="1">
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Destaque</label>
                                                <div class="col-sm-10">
                                                    <div class="col-sm-12 padding-0">
                                                        <?php if ($dados_textopublico): ?>
                                                            <?php if ($dados_textopublico->destaque == 1) : ?>
                                                                <input checked type="checkbox" name="destaque_texto" value="1">
                                                            <?php else : ?>
                                                                <input type="checkbox" name="destaque_texto" value="1">
                                                            <?php endif; ?>
                                                        <?php else : ?>
                                                            <input type="checkbox" name="destaque_texto" value="1">
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; ">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; ">
                                                    <button id = "btnCancelar" type="button" onclick="javascript:window.location.href = '<?= url()->route('textopacientes.index') ?>';" class="btn ripple btn-raised btn-danger">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>


        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.knob.js');?>"></script>
        <script src="<?=assets()->js('plugins/bootstrap-material-datetimepicker.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.mask.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/select2.full.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/nouislider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/ion.rangeSlider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.validate.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/summernote.min.js');?>"></script>


        <script src="<?=assets()->js('main.js');?>"></script>

        <script type="text/javascript">
                                                        $(document).ready(function () {

                                                            $('#summernote').summernote({
                                                                height: 400,
                                                                toolbar: [
                                                                    // [groupName, [list of button]]
                                                                    ['style', ['bold', 'italic', 'underline', 'clear']],
                                                                    ['font', ['strikethrough', 'superscript', 'subscript']],
                                                                    ['para', ['paragraph']],
                                                                    ['picture', ['picture']],
                                                                    ['video', ['video']]
                                                                ]
                                                            });

                                                            var valor = $("#txt_texto").text();
                                                            $('.note-editable').html(valor);
                                                        });

                                                        function validacaoF(form) {
                                                            $('#lbl_nm_texto').removeClass('alertaFrm');
                                                            $('#lbl_chamada_texto').removeClass('alertaFrm');

                                                            if (form.nm_texto.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                                                                form.nm_texto.focus();
                                                                $('#msgformulario').html('Título inválido! Informe-o corretamente.');
                                                                $('#msgformulario').removeClass('alert-primary');
                                                                $('#msgformulario').addClass('alert-danger');
                                                                $('#lbl_nm_texto').addClass('alertaFrm');
                                                                return false;
                                                            } else if (form.chamada_texto.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                                                                form.chamada_texto.focus();
                                                                $('#msgformulario').html('Chamada inválida! Informe-a corretamente.');
                                                                $('#msgformulario').removeClass('alert-primary');
                                                                $('#msgformulario').addClass('alert-danger');
                                                                $('#lbl_chamada_texto').addClass('alertaFrm');
                                                                return false;
                                                            }
                                                        }

                                                        function event_btnEnviarClick()
                                                        {
                                                            var valor = $('.note-editable').html();
                                                            $("#txt_texto").text(valor);

                                                            if (validacaoF(document.frmCadTexto) != false) {
                                                                document.frmCadTexto.submit();
                                                            } else {
                                                                return false;
                                                            }
                                                        }
                                                        $('#btnEnviar').click(event_btnEnviarClick);
        </script>
        <!-- end: Javascript -->
    </body>
</html>