<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <div  id="popup-site">
            <div class="modal-example">
                <div class="col-md-12">
                    <div class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h4 class="modal-title">Deseja excluir este registro?</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Após confirmada, esta operação não poderá ser desfeita!</p>
                                </div>
                                <div class="modal-footer">
                                    <button onclick="javascript:fecharPopupSite()" type="button" class="btn btn-danger">Cancelar</button>
                                    <button id="btnConfirmaPopupSite" onclick="javascript:confirmaPopupSite()" type="button" class="btn btn-success">Confirmar</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
        </div>
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Área Administrativa > Dicionário > Imagens</h3>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="col-md-12">
                    <div class="panel">
                        <?php if (session()->has('_sucesso')): ?>
                            <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?></div>
                        <?php endif; ?>

                        <?php if (session()->has('_erro')): ?>
                            <div class="alert alert-warning" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
                        <?php endif; ?>
                        <div style="height: 67px" class="panel-heading">
                            <h3 style="float: left; width: 150px">Galeria</h3>
                            <div class="col-md-2" style="margin-top:10px; float: right">
                                <button onclick="javascript:window.location.href = '<?= DIR_BASE .'/'. url()->route('dicionario.fileupload', ['id' => url()->getParam('id'), 'tipoimg' => 4]) ?>';" class="btn ripple btn-raised btn-success">
                                    <div>
                                        <span class="fa fa-upload"></span>
                                        <span style="margin-left: 10px;">Upload</span>
                                        <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                    </div>
                                </button>
                            </div>
                            <div class="col-md-2" style="margin-top:10px; float: right">
                                <button onclick="javascript:window.location.href = '<?= DIR_BASE .'/'. url()->route('dicionario.cadastrar', ['id' =>  url()->getParam('id')]) ?>';" class="btn ripple btn-raised btn-success">
                                    <div>
                                        <span class="fa fa-edit"></span>
                                        <span style="margin-left: 10px;">Editar Texto</span>
                                        <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                    </div>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <?php
                                if (empty($dados_img_o)):
                                    echo "<p>&nbsp;&nbsp;&nbsp;&nbsp;Nenhuma imagem encontrada!</p>";
                                else:
                                    foreach ($dados_img_o as $dados):
                                        ?>
                                        <div class="col-sm-6 col-md-2 product-grid">
                                            <div class="thumbnail bg-light-grey">
                                                <div class="img-galeria-admin">
                                                    <img src="<?= URL_IMG_PUBLIC . $dados->url ?>" alt="...">
                                                </div>
                                                <div class="caption" style="padding-bottom: 0">
                                                    <p style="text-align: center"><a href="javascript:abrirPopupSite(<?= $dados->id ?>)" class="btn btn-danger" role="button"><span class="fa fa-trash"></span></a></p>
                                                    <input style="width: 135px;" type="text" value="<?= URL_IMG_PUBLIC . $dados->url ?>">
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach;
                                endif;
                                ?> 
                            </div>
                        </div>
                    </div>

                    <div class="panel">
                        <div style="height: 67px" class="panel-heading">
                            <h3 style="float: left; width: 150px">Destaque</h3>
                            <div class="col-md-2" style="margin-top:10px; float: right">
                                <button onclick="javascript:window.location.href = '<?= DIR_BASE .'/'. url()->route('dicionario.fileupload', ['id' => url()->getParam('id'), 'tipoimg' => 5]) ?>';" class="btn ripple btn-raised btn-success">
                                    <div>
                                        <span class="fa fa-upload"></span>
                                        <span style="margin-left: 10px;">Upload</span>
                                        <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                    </div>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <?php
                                if (empty($dados_img_destaque)):
                                    echo "<p>&nbsp;&nbsp;&nbsp;&nbsp;Nenhuma imagem encontrada!</p>";
                                else:
                                    foreach ($dados_img_destaque as $dados):
                                        ?>
                                        <div class="col-sm-6 col-md-2 product-grid">
                                            <div class="thumbnail bg-light-grey">
                                                <div class="img-galeria-admin">
                                                    <img src="<?= URL_IMG_PUBLIC . $dados->url ?>" alt="...">
                                                </div>
                                                <div class="caption" style="padding-bottom: 0">
                                                    <p style="text-align: center"><a href="javascript:abrirPopupSite(<?= $dados->id ?>)" class="btn btn-danger" role="button"><span class="fa fa-trash"></span></a></p>
                                                    <input style="width: 135px;" type="text" value="<?= URL_IMG_PUBLIC . $dados->url ?>">
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach;
                                endif;
                                ?>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>

        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.knob.js');?>"></script>
        <script src="<?=assets()->js('plugins/bootstrap-material-datetimepicker.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.mask.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/select2.full.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/nouislider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/ion.rangeSlider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.validate.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/holder.min.js');?>"></script>

        <!-- custom -->
        <script src="<?=assets()->js('main.js');?>"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                document.getElementById('popup-site').style.display = 'none';

                var altura = $(document).height();
                $("#popup-site").css({"height": +altura + "px"});

            });

            function fecharPopupSite() {
                document.getElementById('popup-site').style.display = 'none';
            }

            function abrirPopupSite(codigo) {
                document.getElementById('popup-site').style.display = 'block';
                $('#btnConfirmaPopupSite').attr("onclick", 'javascript:confirmaPopupSite(' + codigo + ')');
            }

            function confirmaPopupSite(codigo) {
                window.location.href = '<?= DIR_BASE .'/'. url()->route('dicionario.deleteupload', ['id' => url()->getParam('id')]);?>/idimg/' + codigo;
                fecharPopupSite();
            }
        </script>
        <!-- end: Javascript -->
    </body>
</html>