<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Área Administrativa > Aulas > Imagens > Upload</h3>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="col-md-12">
                    <div class="panel">
                        <form action="<?= DIR_BASE .'/'. url()->route('aulas.saveupload', ['id' => url()->getParam('id'), 'tipoimg' => url()->getParam('tipoimg')]); ?>" method="POST" enctype="multipart/form-data">
                            <div style="height: 67px" class="panel-heading">
                                <h3 style="float: left; width: 300px">Galeria > Upload</h3>
                                <div class="col-md-2" style="margin-top:10px; float: right">
                                    <button type="submit" class="btn ripple btn-raised btn-success">
                                        <div>
                                            <span class="fa fa-plus"></span>
                                            <span style="margin-left: 10px;">Salvar</span>
                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                        </div>
                                    </button>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="input-group fileupload-v1" style="margin-bottom: 10px">
                                            <input type="file" name="file[]" class="fileupload-v1-file hidden"/>
                                            <input type="text" class="form-control fileupload-v1-path" placeholder="Imagem (.jpg, .png, .gif)" disabled>
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v1-btn" type="button"><i class="fa fa-folder"></i> Selecionar</button>
                                            </span>
                                        </div><!-- /input-group -->
                                        <div class="input-group fileupload-v2" style="margin-bottom: 10px">
                                            <input type="file" name="file[]" class="fileupload-v2-file hidden"/>
                                            <input type="text" class="form-control fileupload-v2-path" placeholder="Imagem (.jpg, .png, .gif)" disabled>
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v2-btn" type="button"><i class="fa fa-folder"></i> Selecionar</button>
                                            </span>
                                        </div><!-- /input-group -->
                                        <div class="input-group fileupload-v3" style="margin-bottom: 10px">
                                            <input type="file" name="file[]" class="fileupload-v3-file hidden"/>
                                            <input type="text" class="form-control fileupload-v3-path" placeholder="Imagem (.jpg, .png, .gif)" disabled>
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v3-btn" type="button"><i class="fa fa-folder"></i> Selecionar</button>
                                            </span>
                                        </div><!-- /input-group -->
                                        <div class="input-group fileupload-v4" style="margin-bottom: 10px">
                                            <input type="file" name="file[]" class="fileupload-v4-file hidden"/>
                                            <input type="text" class="form-control fileupload-v4-path" placeholder="Imagem (.jpg, .png, .gif)" disabled>
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v4-btn" type="button"><i class="fa fa-folder"></i> Selecionar</button>
                                            </span>
                                        </div><!-- /input-group -->
                                        <div class="input-group fileupload-v5" style="margin-bottom: 10px">
                                            <input type="file" name="file[]" class="fileupload-v5-file hidden"/>
                                            <input type="text" class="form-control fileupload-v5-path" placeholder="Imagem (.jpg, .png, .gif)" disabled>
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v5-btn" type="button"><i class="fa fa-folder"></i> Selecionar</button>
                                            </span>
                                        </div><!-- /input-group -->
                                    </div><!-- /.col-lg-6 -->
                                </div><!-- /.row -->
                            </div>
                        </form>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->

        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>



        <!-- plugins -->
        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.datatables.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/datatables.bootstrap.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/dropzone.js');?>"></script>


        <!-- custom -->
        <script src="<?=assets()->js('main.js');?>"></script>

        <script type="text/javascript">
            $(document).ready(function () {

            });
        </script>

        <!-- end: Javascript -->
    </body>
</html>