<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <!-- start: Header -->
        <?php $this->render('common/header'); ?> 
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <?php if ($dados): ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Banner > Alterar</h3>
                            <?php else: ?>
                                <h3 class="animated fadeInLeft">Área Administrativa > Banner > Cadastrar</h3>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="form-element">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-12">
                            <div class="panel form-element-padding">
                                <div id="msgformulario" class="alert alert-primary" role="alert">* Campos Obrigatórios!</div>
                                <div class="panel-heading">
                                    <?php if ($dados): ?>
                                        <h4>Banner > Alterar</h4>
                                    <?php else: ?>
                                        <h4>Banner > Novo</h4>
                                    <?php endif; ?>
                                </div>
                                <div class="panel-body" style="padding-bottom:30px;">
                                    <div class="col-md-12">
                                        <form class="cmxform" name="frmCadBanner" method="POST" action="<?= url()->route('banner.salvar'); ?>">
                                            <?php if ($dados): ?>
                                                <input type="hidden" name="id" value="<?= $dados->id; ?>">
                                            <?php endif; ?>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_titulo" class="col-sm-2 control-label text-right">Título</label>
                                                <div class="col-sm-10"><input value="<?= $dados ? $dados->titulo : '' ?>" name="titulo" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label id="lbl_subtitulo" class="col-sm-2 control-label text-right">Subtítulo*</label>
                                                <div class="col-sm-10"><input value="<?= $dados ? $dados->subtitulo : '' ?>" name="subtitulo" required aria-required="true" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Descrição</label>
                                                <div class="col-sm-10"><input value="<?= $dados ? $dados->descricao : '' ?>" name="descricao" type="text" class="form-control"></div>
                                            </div>
                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Link</label>
                                                <div class="col-sm-10"><input value="<?= $dados ? $dados->link : '' ?>" name="link" type="text" class="form-control"></div>
                                            </div>

                                            <div class="col-md-12" style="padding-bottom: 10px"><label class="col-sm-2 control-label text-right">Ativo</label>
                                                <div class="col-sm-10">
                                                    <div class="col-sm-12 padding-0">
                                                        <?php if ($dados): ?>
                                                            <?php if ($dados->ativo == 1) : ?>
                                                                <input checked type="checkbox" name="ativo_membro" value="1">
                                                            <?php else : ?>
                                                                <input type="checkbox" name="ativo_membro" value="1">
                                                            <?php endif; ?>
                                                        <?php else : ?>
                                                            <input type="checkbox" name="ativo_membro" value="1">
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <div class="col-md-12" style="padding-bottom: 10px">
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button id="btnEnviar" class="btn ripple btn-raised btn-success">
                                                        <div>
                                                            <span class="fa fa-save"></span>
                                                            <span style="margin-left: 10px;">Salvar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                                <div class="col-md-3" style="margin-top:10px; float: right">
                                                    <button onclick="javascript:window.location.href = 'banner.index';" class="btn ripple btn-raised btn-danger">
                                                        <div>
                                                            <span class="fa fa-close"></span>
                                                            <span style="margin-left: 10px;">Cancelar</span>
                                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                                        </div>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="<?=assets()->js('jquery.min.js');?>"></script>
        <script src="<?=assets()->js('jquery.ui.min.js');?>"></script>
        <script src="<?=assets()->js('bootstrap.min.js');?>"></script>


        <!-- plugins -->
        <script src="<?=assets()->js('plugins/moment.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.knob.js');?>"></script>
        <script src="<?=assets()->js('plugins/bootstrap-material-datetimepicker.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.nicescroll.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.mask.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/select2.full.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/nouislider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/ion.rangeSlider.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/jquery.validate.min.js');?>"></script>
        <script src="<?=assets()->js('plugins/summernote.min.js');?>"></script>


        <script src="<?=assets()->js('main.js');?>"></script>
        <script type="text/javascript">

            function validacaoF(form) {
                $('#lbl_subtitulo').removeClass('alertaFrm');

                if (form.subtitulo.value.replace(/^\s+|\s+$/g, "").length <= 3) {
                    form.subtitulo.focus();
                    $('#msgformulario').html('Nome inválido! Informe-o corretamente.');
                    $('#msgformulario').removeClass('alert-primary');
                    $('#msgformulario').addClass('alert-danger');
                    $('#lbl_subtitulo').addClass('alertaFrm');
                    return false;
                }
            }

            function event_btnEnviarClick()
            {
                if (validacaoF(document.frmCadBanner) != false) {
                    document.frmCadBanner.submit();
                } else {
                    return false;
                }
            }

            $('#btnEnviar').click(event_btnEnviarClick);
        </script>
        <!-- end: Javascript -->
    </body>
</html>