<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <div  id="popup-site">
            <div class="modal-example">
                <div class="col-md-12">
                    <div class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h4 class="modal-title">Deseja excluir este registro?</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Após confirmada, esta operação não poderá ser desfeita!</p>
                                </div>
                                <div class="modal-footer">
                                    <button onclick="javascript:fecharPopupSite()" type="button" class="btn btn-danger">Cancelar</button>
                                    <button id="btnConfirmaPopupSite" onclick="javascript:confirmaPopupSite()" type="button" class="btn btn-success">Confirmar</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
        </div>
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Área Administrativa > Equipe > Imagens</h3>

                            <ul class="nav navbar-nav">
                                <li><a href="<?= url()->route('index') ?>">Início</a></li>
                                <li><a href="<?= url()->route('clinica.index') ?>">A clínica</a></li>
                                <li><a href="<?= url()->route('tratamentos.index') ?>">Tratamentos</a></li>
                                <li><a href="<?= url()->route('equipe.index') ?>">Equipe</a></li>
                                <li><a href="<?= url()->route('artigos.index') ?>">Artigos</a></li>
                                <li><a href="<?= url()->route('depoimentos.index') ?>">Depoimentos</a></li>
                                <li><a href="<?= url()->route('nutricaofitness.index') ?>">Nutrição e Fitness</a></li>
                                <li><a href="<?= url()->route('receitas.index') ?>">Receitas</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->
                <div class="col-md-12">
                    <div class="panel">
                        <?php if (session()->has('_sucesso')): ?>
                            <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?></div>
                        <?php endif; ?>

                        <?php if (session()->has('_erro')): ?>
                            <div class="alert alert-warning" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
                        <?php endif; ?>
                        <div style="height: 67px" class="panel-heading">
                            <h3 style="float: left; width: 150px">Destaque</h3>
                            <div class="col-md-2" style="margin-top:10px; float: right">
                                <button onclick="javascript:window.location.href = '<?= url()->route('equipe.fileupload', ['id' => input()->get('id')]) ?>';" class="btn ripple btn-raised btn-success">
                                    <div>
                                        <span class="fa fa-upload"></span>
                                        <span style="margin-left: 10px;">Upload</span>
                                        <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                    </div>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <?php
                                if (is_null($dados_equipe->foto_membro)):
                                    echo "<p>&nbsp;&nbsp;&nbsp;&nbsp;Nenhuma imagem encontrada!</p>";
                                else:
                                    ?>
                                    <div class="col-sm-6 col-md-2 product-grid">
                                        <div class="thumbnail bg-light-grey">
                                            <div class="img-galeria-admin">
                                                <img src="<?= URL_IMG_PUBLIC . $dados_equipe->foto_membro ?>">
                                            </div>
                                            <div class="caption" style="padding-bottom: 0">
                                                <p style="text-align: center"><a href="javascript:abrirPopupSite()" class="btn btn-danger" role="button"><span class="fa fa-trash"></span></a></p>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="../asset/js/jquery.min.js"></script>
        <script src="../asset/js/jquery.ui.min.js"></script>
        <script src="../asset/js/bootstrap.min.js"></script>


        <!-- plugins -->
        <script src="../asset/js/plugins/moment.min.js"></script>
        <script src="../asset/js/plugins/holder.min.js"></script>
        <script src="../asset/js/plugins/jquery.knob.js"></script>
        <script src="../asset/js/plugins/ion.rangeSlider.min.js"></script>
        <script src="../asset/js/plugins/bootstrap-material-datetimepicker.js"></script>
        <script src="../asset/js/plugins/jquery.nicescroll.js"></script>
        <script src="../asset/js/plugins/jquery.mask.min.js"></script>
        <script src="../asset/js/plugins/select2.full.min.js"></script>
        <script src="../asset/js/plugins/nouislider.min.js"></script>
        <script src="../asset/js/plugins/jquery.validate.min.js"></script>
        <script src="../asset/js/plugins/summernote.min.js"></script>


        <!-- custom -->
        <script src="../asset/js/main.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                document.getElementById('popup-site').style.display = 'none';

                var altura = $(document).height();
                $("#popup-site").css({"height": +altura + "px"});

            });

            function fecharPopupSite() {
                document.getElementById('popup-site').style.display = 'none';
            }

            function abrirPopupSite() {
                document.getElementById('popup-site').style.display = 'block';
                $('#btnConfirmaPopupSite').attr("onclick", 'javascript:confirmaPopupSite()');
            }

            function confirmaPopupSite() {
                window.location.href = '<?= url()->route('equipe.deleteupload', ['id' => input()->get('id')]); ?>';
                fecharPopupSite();
            }
        </script>
        <!-- end: Javascript -->
    </body>
</html>