<!DOCTYPE HTML>
<html>

<head>
	<title><?= $dados_dicionario->titulo ?></title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="<?= assets()->css('main.css'); ?>" />
	<noscript>
		<link rel="stylesheet" href="<?= assets()->css('noscript.css'); ?>" /></noscript>
</head>

<body class=" is-preload">

	<!-- Wrapper -->
	<div id="wrapper">
  
		<!-- Intro -->
		<div id="intro">
			<h1><?= $dados_dicionario->titulo ?></h1>
			<p><?= $dados_dicionario->chamada ?></p>
			<ul class="actions">
				<li><a href="#header" class="button icon solid solo fa-arrow-down scrolly">Continue</a></li>
			</ul>
		</div>

		<!-- Header -->
		<header id="header">
			<a href="<?=$dados_dicionario->id?>" class="logo">Dicionário</a>
		</header>

		<!-- Nav -->
		<nav id="nav">
			<ul class="links">
				<li><a href="/">Home</a></li>
				<li><a href="<?=DIR_BASE?>/dicas">Dicas</a></li>
				<li><a href="<?=DIR_BASE?>/aulas">Aulas</a></li> 
				<li><a href="<?=DIR_BASE?>/novidades">Novidades</a></li>
				<li class="active"><a href="<?=DIR_BASE?>/dicionario">Dicionário</a></li>
				<li><a href="<?=DIR_BASE?>/contact">Contato</a></li>
			</ul>
			<!-- Inclusão dos ícones -->
			<?php $this->render('common/nav-icons', ['dados_redes_sociais' => $dados_redes_sociais]) ?>
		</nav>

		<!-- Main -->
		<div id="main">

			<!-- Post -->
			<section class="post">
				<header class="major">
					<span class="date mb-4!important"><?= $dados_dicionario->dt_exibe ?></span>
					<h1><?= $dados_dicionario->titulo ?> </h1>
					<p><?= $dados_dicionario->chamada ?></p>
				</header>
				<div class="image main"><img src="<?= assets()->img("pic01.jpg") ?>" alt="" /></div>
                <p><?= $dados_dicionario->conteudo ?></p>
			</section>

			<ul class="actions special">
				<li><a href="<?=DIR_BASE?>/dicionario" class="button large">Voltar para Dicionário</a></li>
			</ul>
		</div>

		<!-- Copyright -->
		<div id="copyright">
			<ul>
				<li>&copy; Untitled</li>
				<li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
			</ul>
		</div>

	</div>

	<!-- Scripts -->
	<script src="<?= assets()->js("jquery.min.js") ?>"></script>
	<script src="<?= assets()->js("jquery.scrollex.min.js") ?>"></script>
	<script src="<?= assets()->js("jquery.scrolly.min.js") ?>"></script>
	<script src="<?= assets()->js("browser.min.js") ?>"></script>
	<script src="<?= assets()->js("breakpoints.min.js") ?>"></script>
	<script src="<?= assets()->js("util.js") ?>"></script>
	<script src="<?= assets()->js("main.js") ?>"></script>

</body>

</html>