<!DOCTYPE html>
<html lang="pt-br">
    <!-- start: Head -->
    <?php $this->render('common/head'); ?>
    <!-- end: Head -->

    <body id="mimin" class="dashboard">
        <div  id="popup-site">
            <div class="modal-example">
                <div class="col-md-12">
                    <div class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h4 class="modal-title">Deseja excluir este registro?</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Após confirmada, esta operação não poderá ser desfeita!</p>
                                </div>
                                <div class="modal-footer">
                                    <button onclick="javascript:fecharPopupSite()" type="button" class="btn btn-danger">Cancelar</button>
                                    <button id="btnConfirmaPopupSite" onclick="javascript:confirmaPopupSite()" type="button" class="btn btn-success">Confirmar</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
        </div>
        <!-- start: Header -->
        <?php $this->render('common/header'); ?>
        <!-- end: Header -->

        <div class="container-fluid mimin-wrapper">

            <!-- start: Left Menu -->
            <?php $this->render('common/leftMenu'); ?>
            <!-- end: Left Menu -->

            <!-- start: content -->
            <div id="content">
                <!-- start: Top Menu -->
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-md-12 col-sm-12">
                            <h3 class="animated fadeInLeft">Área Administrativa > Equipe</h3>

                            <ul class="nav navbar-nav">
                                <li><a href="<?= url()->route('index') ?>">Início</a></li>
                                <li><a href="<?= url()->route('clinica.index') ?>">A clínica</a></li>
                                <li><a href="<?= url()->route('tratamentos.index') ?>">Tratamentos</a></li>
                                <li><a href="<?= url()->route('equipe.index') ?>">Equipe</a></li>
                                <li><a href="<?= url()->route('artigos.index') ?>">Artigos</a></li>
                                <li><a href="<?= url()->route('depoimentos.index') ?>">Depoimentos</a></li>
                                <li><a href="<?= url()->route('nutricaofitness.index') ?>">Nutrição e Fitness</a></li>
                                <li><a href="<?= url()->route('receitas.index') ?>">Receitas</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end: Top Menu -->

                <!-- start: conteúdo central -->

                <div class="col-md-12 top-20 padding-0 modal-example">
                    <div class="col-md-12">
                        <div class="panel">
                            <?php if (session()->has('_sucesso')): ?>
                                <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?></div>
                            <?php endif; ?>

                            <?php if (session()->has('_erro')): ?>
                                <div class="alert alert-warning" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
                            <?php endif; ?>
                            <div style="height: 67px" class="panel-heading">
                                <h3 style="float: left; width: 150px">Equipe</h3>
                                <div class="col-md-2" style="margin-top:10px; float: right">
                                    <button onclick="javascript:window.location.href = '<?=url()->route('equipe.cadastrar')?>';" class="btn ripple btn-raised btn-success">
                                        <div>
                                            <span class="fa fa-plus"></span>
                                            <span style="margin-left: 10px;">Novo</span>
                                            <span class="ink animate" style="height: 87px; width: 87px; top: -35.5px; left: -1px;"></span>
                                        </div>
                                    </button>
                                </div>
                            </div>
                            <div class="panel-body">



                                <div class="responsive-table">
                                    <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>Data</th>
                                                <th style="width: 35px;">Ativo</th>
                                                <th style="width: 35px;">Foto</th>
                                                <th style="width: 35px;">Editar</th>
                                                <th style="width: 35px;">Excluir</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($dados_equipe as $dados): ?>
                                                <tr>
                                                    <td><?= $dados->cd_membro ?></td>
                                                    <td><?= $dados->nm_membro ?></td>
                                                    <td><?= date('d/m/Y',strtotime($dados->dt_cadastro_membro)) ?></td>
                                                    <td align="center">
                                                        <div class="form-group form-animate-checkbox">
                                                            <?php if ($dados->ativo_membro == 1): ?>
                                                                <input disabled="true" checked type="checkbox" class="checkbox">
                                                            <?php else: ?>
                                                                <input disabled="true" type="checkbox" class="checkbox">
                                                            <?php endif; ?>
                                                        </div>
                                                    </td>
                                                    <td align="center">
                                                        <button onclick="javascript:window.location.href = '<?=url()->route('equipe.imagens',['id'=>$dados->cd_membro])?>';" style="height: 20px; width: 40px; padding: 0;" class="btn ripple btn-raised btn-info">
                                                            <span class="fa fa-upload"></span>
                                                        </button>
                                                    </td>
                                                    <td align="center">
                                                        <button onclick="javascript:window.location.href = '<?=url()->route('equipe.cadastrar',['id'=>$dados->cd_membro])?>';" style="height: 20px; width: 40px; padding: 0;" class="btn ripple btn-raised btn-info">
                                                            <span class="fa fa-edit"></span>
                                                        </button>
                                                    </td>
                                                    <td align="center">
                                                        <button  onclick="javascript:abrirPopupSite(<?= $dados->cd_membro ?>)" style="height: 20px; width: 40px; padding: 0;" class="btn ripple btn-raised btn-danger">
                                                            <span class="fa fa-trash"></span>
                                                        </button>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: conteúdo central -->
            </div>
            <!-- end: content -->
        </div>

        <!-- start: Mobile -->
        <?php $this->render('common/mobileMenu'); ?>
        <!-- end: Mobile -->


        <!-- start: Javascript -->
        <script src="../asset/js/jquery.min.js"></script>
        <script src="../asset/js/jquery.ui.min.js"></script>
        <script src="../asset/js/bootstrap.min.js"></script>



        <!-- plugins -->
        <script src="../asset/js/plugins/moment.min.js"></script>
        <script src="../asset/js/plugins/jquery.datatables.min.js"></script>
        <script src="../asset/js/plugins/datatables.bootstrap.min.js"></script>
        <script src="../asset/js/plugins/jquery.nicescroll.js"></script>


        <!-- custom -->
        <script src="../asset/js/main.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#datatables-example').DataTable();
                document.getElementById('popup-site').style.display = 'none';

                var altura = $(document).height();
                $("#popup-site").css({"height": +altura + "px"});

            });

            function fecharPopupSite() {
                document.getElementById('popup-site').style.display = 'none';
            }

            function abrirPopupSite(codigo) {
                document.getElementById('popup-site').style.display = 'block';
                $('#btnConfirmaPopupSite').attr("onclick", 'javascript:confirmaPopupSite(' + codigo + ')');
            }

            function confirmaPopupSite(codigo) {
                window.location.href = '<?=  url()->route('equipe.excluir')?>&id='+ codigo;
                fecharPopupSite();
            }
        </script>

        <!-- end: Javascript -->
    </body>
</html>