<!-- Footer Area -->
<footer class="footer_area">
    <div class="container">
        <div class="footer_row row">
            <div class="col-md-4 col-sm-6 footer_about">
                <h2>Genética Médica HC/UFMG</h2>
                <img src="<?=assets()->img('logo.png')?>" alt="">

            </div>
            <div class="col-md-4 col-sm-6 footer_about quick">
                <h2>Links relacionados</h2>
                <ul class="quick_link">
                    <?php foreach ($dados_sitesrelacionados as $key => $value) : ?>
                        <li><a target="_blank" href="<?=$value->link?>" title="<?=$value->nome?>"><i class="fa fa-chevron-right"></i><?=$value->nome?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="col-md-4 col-sm-6 footer_about">
                <h2>CONTATO</h2>
                <address>
                    <p>Entre em contato:</p>
                    <ul class="my_address">
                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i><?=$dados_configprincipais[0]->email_principal?></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i><?=$dados_configprincipais[0]->instagram?></a></li>
                        <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i><?=$dados_configprincipais[0]->telefone1?></a></li>
                        <li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i><?=$dados_configprincipais[0]->endereco1?></a></li>
                    </ul>
                </address>
            </div>
        </div>
    </div>
    <div class="copyright_area">
        Copyright 2019 All rights reserved. Developed by <a href="http://www.compnum.com">Compnum</a>
    </div>
</footer>
<!-- End Footer Area -->

<!-- jQuery JS -->
<script src="<?=assets()->js('jquery-1.12.0.min.js');?>"></script>
<!-- Bootstrap JS -->
<script src="<?=assets()->js('bootstrap.min.js');?>"></script>
<!-- Animate JS -->
<script src="<?=assets()->vendors('animate/wow.min.js');?>"></script>
<!-- Camera Slider -->
<script src="<?=assets()->vendors('camera-slider/jquery.easing.1.3.js');?>"></script>
<script src="<?=assets()->vendors('camera-slider/camera.min.js');?>"></script>
<!-- Isotope JS -->
<script src="<?=assets()->vendors('isotope/imagesloaded.pkgd.min.js');?>"></script>
<script src="<?=assets()->vendors('isotope/isotope.pkgd.min.js');?>"></script>
<!-- Progress JS -->
<script src="<?=assets()->vendors('Counter-Up/jquery.counterup.min.js');?>"></script>
<script src="<?=assets()->vendors('Counter-Up/waypoints.min.js');?>"></script>
<!-- Owlcarousel JS -->
<script src="<?=assets()->vendors('owl_carousel/owl.carousel.min.js');?>"></script>
<!-- Stellar JS -->
<script src="<?=assets()->vendors('stellar/jquery.stellar.js');?>"></script>
<!-- Theme JS -->
<script src="<?=assets()->js('theme.js');?>"></script>