    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="resource-types" content="document" >
    <meta name="revisit-after" content="1" >
    <meta name="classification" content="Internet" >
    <meta name="robots" content="ALL" >
    <meta name="distribution" content="Global" >
    <meta name="rating" content="General" >
    <meta name="author" content="Daniel Viana - Compnum" >
    <meta name="language" content="pt-br" >
    <meta name="doc-class" content="Completed" >
    <meta name="doc-rights" content="private" >
    <meta name="url" content="<?= DIR_BASE ?>" >
    <base href="<?= DIR_BASE ?>">

    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?=assets()->js('html5shiv.min.js');?>"></script>
    <script src="<?=assets()->js('respond.min.js');?>"></script>
    <![endif]-->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?=assets()->css('bootstrap.min.css');?>" type="text/css" >
    <!-- Animate CSS -->
    <link rel="stylesheet" href="<?=assets()->vendors('animate/animate.css') ?>">
    <!-- Icon CSS-->
    <link rel="stylesheet" href="<?=assets()->vendors('font-awesome/css/font-awesome.min.css') ?>">
    <!-- Camera Slider -->
    <link rel="stylesheet" href="<?=assets()->vendors('camera-slider/camera.css') ?>">
    <!-- Owlcarousel CSS-->
    <link rel="stylesheet" href="<?=assets()->vendors('owl_carousel/owl.carousel.css') ?>" type="text/css" media="all">
    <!--Theme Styles CSS-->
    <link rel="stylesheet" href="<?=assets()->css('style.css');?>" type="text/css" media="all">

    <!-- Favicon -->
    <link rel="icon" href="/public/favicon.png" type="image/x-icon" />
