<ul class="icons">
    <li><a href="<?= $dados_redes_sociais[0]->twitter ?>" target="_blank" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
    <li><a href="<?= $dados_redes_sociais[0]->linkedin ?>" target="_blank" class="icon brands fa-linkedin"><span class="label">Linkedin</span></a></li>
    <li><a href="<?= $dados_redes_sociais[0]->instagram ?>" target="_blank" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
    <li><a href="<?= $dados_redes_sociais[0]->github ?>" target="_blank" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
</ul>